name: core
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  formz: ^0.8.0
  flutter_bloc: ^8.1.6
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2
  firebase_remote_config: ^5.1.4
  google_mobile_ads: ^5.2.0
  dartz: ^0.10.1
  get_it: ^8.0.2
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: br.com.wcastro.core
    iosBundleIdentifier: br.com.wcastro.core
